### ISSUE TITLE
Add Linear Search in C

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/HacktoberFest#10]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by Feynman3142** [comment]
I want to claim this

**Comment by shiva1208** [comment]
I want to take it.

**Comment by omkarprabhu-98** [comment]
i want  to claim this

**Comment by smarty1palak** [comment]
i claim this

**Comment by ag1709** [comment]
I claim it

**Comment by QuaffleBlood** [comment]
I CLAIM THIS

**Comment by shiva1208** [comment]
Yes I want to claim it...

**Comment by pankajc007** [comment]
i want to claim this

**Comment by adityaa16maan** [comment]
i want to claim this

**Comment by Djarpit** [comment]
i want to claim this

**Comment by Djarpit** [comment]
i want to cliam this

**Comment by sujaydcss** [comment]
i want to claim this
