### ISSUE TITLE
Add Binary Search in C

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/HacktoberFest#11]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by Arunraj97** [comment]
I(Arunraj) am working on it

**Comment by mahim23** [comment]
I claim it

**Comment by omkarprabhu-98** [comment]
i want to claim this

**Comment by smarty1palak** [comment]
i claim this

**Comment by ag1709** [comment]
I claim it

**Comment by rajitaaa** [comment]
I claim it

**Comment by pankajc007** [comment]
i want to claim this

**Comment by adityaa16maan** [comment]
i want to claim this.

**Comment by Djarpit** [comment]
i claim this

**Comment by sujaydcss** [comment]
i want to claim this
