### ISSUE TITLE
Add Documentation for Selection Sort

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/HacktoberFest#12]
Explain the basic concept of the Algorithm in the README.md file in the folder!

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by DrEAmRBoY** [comment]
i claim this

**Comment by MayankTripathi01** [comment]
i claim this
