### ISSUE TITLE
Add 'Hello World' in Ruby

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/HacktoberFest#16]
**Note:**
This is an admin-only Issue used only for demonstration! Do not claim this Issue. Your PR for this will not be accepted at any costs!

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by Saichu123** [comment]
I claim it

**Comment by salman-bhai** [comment]
@Saichu123 reference the Issue when you send a Pull Request!

**Comment by jobsrawat** [comment]
i claim it

**Comment by Att4ck3rS3cur1ty** [comment]
I claim it!

**Comment by Att4ck3rS3cur1ty** [comment]
I claim it!
