### ISSUE TITLE
Add Hello World in C

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/HacktoberFest#2]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by mirthunraj** [comment]
Mirthunraj: I claim this

**Comment by Anirudh0707** [comment]
I would like to take this up

**Comment by niharock69** [comment]
i claim this

**Comment by MayankTripathi01** [comment]
i want to claim this

**Comment by nimish04** [comment]
i want to claim this

**Comment by mahim23** [comment]
I claim it

**Comment by omkarprabhu-98** [comment]
i want to claim it

**Comment by smarty1palak** [comment]
i claim this

**Comment by ag1709** [comment]
I claim it

**Comment by QuaffleBlood** [comment]
I CLAIM THIS

**Comment by novicecoder113** [comment]
I want to do it

**Comment by salman-bhai** [comment]
Calm down people! . Just send all your Pull Requests.

**Comment by Feynman3142** [comment]
I claim this

**Comment by pankajc007** [comment]
i claim this

**Comment by Namrata7199** [comment]
i claim this

**Comment by nimish04** [comment]
I want to claim it.

**Comment by adityaa16maan** [comment]
I claim it.

**Comment by salman-bhai** [comment]
Guys solve the other issues!
