### ISSUE TITLE
Not showing all list form command 

### ISSUE THREAD

**Issue by jsroyal** [IEEE-NITK/HacktoberFest#222]
List all currently configured remote repositories:

$ git remote -v

**Comment by salman-bhai** [comment]
@chinmaydd please help here! I can't solve this!

**Comment by jsroyal** [comment]
@salman-bhai This command did you find anywhere?

**Comment by salman-bhai** [comment]
Yeah sorry I forgot about this! Take a look [here](https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes)

**Comment by jsroyal** [comment]
@salman-bhai  Thanks.
