### ISSUE TITLE
Add Hello World in C++

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/HacktoberFest#3]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by DrEAmRBoY** [comment]
I wanna do this xD. I claim. K whatever.

**Comment by MayankTripathi01** [comment]
i wanna claim this

**Comment by omkarprabhu-98** [comment]
i want to claim this

**Comment by omkarprabhu-98** [comment]
i want to claim this

**Comment by mahim23** [comment]
I want to claim it

**Comment by pankajc007** [comment]
i want to claim this

**Comment by ag1709** [comment]
I claim it

**Comment by MathewMedayil** [comment]
i want to claim this

**Comment by adityaa16maan** [comment]
i want to claim this.

**Comment by Tilak-N-Shenoy** [comment]
i want to claim this
[hii.txt](https://github.com/IEEE-NITK/HacktoberFest/files/552768/hii.txt)

**Comment by salman-bhai** [comment]
Guys look at other Issues!
