### ISSUE TITLE
Add Hello World in Java

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/HacktoberFest#4]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by mishal23** [comment]
i claim it

**Comment by yash1401** [comment]
i claim it

**Comment by omkarprabhu-98** [comment]
i want to claim this

**Comment by mahim23** [comment]
I wanna claim it

**Comment by ag1709** [comment]
I claim it

**Comment by sujaydcss** [comment]
i want to claim this

**Comment by AsteveJ** [comment]
i want to claim this
