### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/HacktoberFest#6]
Click on the link [here](https://github.com/salman-bhai/DA_A_DS/blob/master/CONTRIBUTING.md) to see an example.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by DrEAmRBoY** [comment]
I claim this

**Comment by MayankTripathi01** [comment]
i claim

**Comment by salman-bhai** [comment]
Go ahead! Send a Pull Request.
