### ISSUE TITLE
Add Bubble Sort Algorithm

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/HacktoberFest#8]
Ground rules:

1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by Namrata7199** [comment]
I want to claim this

**Comment by omkarprabhu-98** [comment]
i want to claim this

**Comment by smarty1palak** [comment]
I want to claim this

**Comment by QuaffleBlood** [comment]
I WANT TO CLAIM THIS

**Comment by Arunraj97** [comment]
claiming this

**Comment by shiva1208** [comment]
I want to claim.

**Comment by yash1401** [comment]
i claim

**Comment by sujaydcss** [comment]
I want to claim this

**Comment by Djarpit** [comment]
i claim this
