### ISSUE TITLE
Add Selection Sort in C

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/HacktoberFest#9]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

**Comment by pankajc007** [comment]
i ma taking it

**Comment by NachiketUN** [comment]
I want to claim this.

**Comment by omkarprabhu-98** [comment]
i want to claim this

**Comment by smarty1palak** [comment]
i claim this

**Comment by ag1709** [comment]
I claim it

**Comment by QuaffleBlood** [comment]
I WANT THIS

**Comment by Feynman3142** [comment]
I claim this

**Comment by sujaydcss** [comment]
i want to claim this

**Comment by neerajkumarjaiswal** [comment]
I want to claim.

**Comment by Anirudh0707** [comment]
I would like to take this up
